# Generated by Django 2.0.5 on 2018-05-17 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('srcLink', models.CharField(blank=True, max_length=250, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('fileType', models.CharField(blank=True, max_length=10)),
                ('price', models.FloatField(default=0)),
                ('ownuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watermark_song',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='songs',
            field=models.ManyToManyField(to='watermark.Song'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
